spring:
  application:
    name: tech-notes
  data:
    redis:
      port: 6379
      host: 192.168.80.128
      database: 0
      timeout: 2000
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 2000
          enabled: on
  mail:
    host: smtp.gmail.com
    port: 465
    username: chwmwei@gmail.com
    password: "dczdjurfepcparjk"
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
    protocol: smtps
    default-encoding: UTF-8
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.80.128:3306/tech_notes?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 12345678
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secret: mySecretKey
  expiration: 2592000

#jasypt:
#  encryptor:
#    algorithm: PBEWITHSHA256AND256BITAES-CBC-BC
#    password: ${JASYPT_ENCRYPTOR_PASSWORD}



management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      access: unrestricted
  metrics:
    distribution:
      percentiles:
        http:
          server:
            requests: 0.5, 0.75, 0.9, 0.95, 0.99
logging:
  level:
    root: info
    com.mwu: debug
    org.springframework.web.filter: debug # 监控过滤器日志
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/app.log
server:
  port: 8081

  address: 0.0.0.0
# 自定义邮件配置
mail:
  verify-code:
    expire-minutes: 15  # 验证码过期时间 15 min
    limit-expire-seconds: 60  # 发送过一次验证码后，在 60s 内不能再发送验证码，用于限流
    template-path: "templates/mail/verify-code.html"
